#!/usr/bin/env bash

set -e
shopt -s nullglob

EXPECTED_ARTIFACTS=(
  dist/artifacts/k3s
  dist/artifacts/k3s-airgap-images-amd64.tar
  dist/artifacts/k3s-airgap-images-amd64.tar.gz
  dist/artifacts/k3s-airgap-images-amd64.tar.zst
  dist/artifacts/k3s-airgap-images-arm.tar
  dist/artifacts/k3s-airgap-images-arm.tar.gz
  dist/artifacts/k3s-airgap-images-arm.tar.zst
  dist/artifacts/k3s-airgap-images-arm64.tar
  dist/artifacts/k3s-airgap-images-arm64.tar.gz
  dist/artifacts/k3s-airgap-images-arm64.tar.zst
  dist/artifacts/k3s-arm64
  dist/artifacts/k3s-armhf
  dist/artifacts/k3s-riscv64
  dist/artifacts/k3s.exe
  dist/artifacts/k3s-images.txt
  dist/artifacts/sha256sum-amd64.txt
  dist/artifacts/sha256sum-arm.txt
  dist/artifacts/sha256sum-arm64.txt
  dist/artifacts/sha256sum-riscv64.txt
  dist/artifacts/sha256sum-windows-amd64.txt
)

CURRENT_ARTIFACTS=(
  dist/artifacts/k3s*
  dist/artifacts/sha256sum*
)

EXPECTED=$(printf '%s\n' "${EXPECTED_ARTIFACTS[@]}" | sort)
CURRENT=$(printf '%s\n' "${CURRENT_ARTIFACTS[@]}" | sort)

UNEXPECTED=$(comm -13 <(printf '%s\n' "${EXPECTED}") <(printf '%s\n' "${CURRENT}"))
MISSING=$(comm -23 <(printf '%s\n' "${EXPECTED}") <(printf '%s\n' "${CURRENT}"))

if [[ -n "${UNEXPECTED}" ]] || [[ -n "${MISSING}" ]]; then
  echo "Unexpected Files: " ${UNEXPECTED}
  echo "Missing Files:    " ${MISSING}
  exit 1
fi
