name: Build K3s

on: 
  workflow_call:
    inputs:
      arch:
        type: string
        description: 'Architecture to build (ubuntu-latest or ubuntu-24.04-arm)'
        default: 'ubuntu-latest'
      os:
        type: string
        description: 'Target OS (linux or windows)'
        default: 'linux'
      upload-image:
        type: boolean
        required: false
        default: false

permissions:
  contents: read

jobs:
  build:
    name: Build K3s
    runs-on: ${{ inputs.arch }}
    timeout-minutes: 20
    env:
      BIN_EXT: ${{ inputs.os == 'windows' && '.exe' || '' }}
      ARTIFACT_EXT: ${{ inputs.os == 'windows' && '-windows' || (contains(inputs.arch, 'arm') && '-arm64' || '') }}
      GOOS: ${{ inputs.os }}
    steps:
    - name: Checkout K3s
      uses: actions/checkout@v4
      
    - name: Build K3s binary
      run: |
        make local-binary
        sha256sum dist/artifacts/k3s${{ env.BIN_EXT }} | sed 's|dist/artifacts/||' > dist/artifacts/k3s${{ env.BIN_EXT }}.sha256sum
    
    - name: Build K3s image
      if: inputs.upload-image == true && inputs.os == 'linux'
      run: ./scripts/package-image
      
    - name: "Save K3s image"
      if: inputs.upload-image == true && inputs.os == 'linux'
      run: docker image save rancher/k3s -o ./dist/artifacts/k3s-image.tar
      
    - name: "Upload K3s Artifacts"
      uses: actions/upload-artifact@v4
      with:
        name: k3s${{ env.ARTIFACT_EXT }}
        path: dist/artifacts/k3s*