name: Build K3s

on: 
  workflow_call:
   inputs:
    upload-repo:
      type: boolean
      required: false
      default: false
    upload-image:
      type: boolean
      required: false
      default: false

permissions:
  contents: read

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    timeout-minutes: 20
    steps:
    - name: Checkout K3s
      uses: actions/checkout@v4
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Build K3s binary
      run: |
        DOCKER_BUILDKIT=1 SKIP_AIRGAP=1 SKIP_VALIDATE=1 GOCOVER=1 make
        sha256sum dist/artifacts/k3s > dist/artifacts/k3s.sha256sum
    - name: bundle repo
      if: inputs.upload-repo == true
      run: |
        tar -czvf ../k3s-repo.tar.gz .
        mv ../k3s-repo.tar.gz .
    - name: "Upload K3s directory"
      if: inputs.upload-repo == true
      uses: actions/upload-artifact@v3
      with:
        name: k3s-repo.tar.gz
        path: k3s-repo.tar.gz
    - name: "Upload K3s binary"
      if: inputs.upload-repo == false
      uses: actions/upload-artifact@v3
      with:
        name: k3s
        path: dist/artifacts/k3s*
    - name: "Save K3s Docker Image"
      if: inputs.upload-image == true
      run: docker image save -o /tmp/k3s-image.tar rancher/k3s
    - name: "Upload K3s Docker Image"
      if: inputs.upload-image == true
      uses: actions/upload-artifact@v3
      with:
        name: k3s-docker
        path: /tmp/k3s-image.tar