name: K3s Docker Tests
on: 
  push:
    paths-ignore:
      - "**.md"
      - "channel.yaml"
      - "install.sh"
      - "tests/**"
      - "!tests/docker-tests**"
      - ".github/**"
      - "!.github/workflows/docker-tests.yaml"
  pull_request:
    paths-ignore:
      - "**.md"
      - "channel.yaml"
      - "install.sh"
      - "tests/**"
      - "!tests/docker-tests**"
      - ".github/**"
      - "!.github/workflows/docker-tests.yaml"
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  build:
    name: Build K3s Docker Image
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        driver-opts: network=host
    - name: Run Dapper Build
      run: |
        SKIP_VALIDATE=true SKIP_AIRGAP=true make
        docker image save -o /tmp/k3s-image.tar rancher/k3s
    - name: Upload K3s image
      uses: actions/upload-artifact@v4
      with:
        name: k3s-docker
        path: /tmp/k3s-image.tar
  
  test:
    needs: build
    name: Run K3s Docker Tests
    runs-on: ubuntu-22.04
    timeout-minutes: 30
    strategy:
      matrix:
        dtest: [basics, bootstraptoken, cacerts, compat, lazypull, upgrade]
      max-parallel: 4
    env:
      GH_MATRIX: ${{ matrix.dtest }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        # network=host driver-opt needed to push to local registry
        driver-opts: network=host
    - name: Download K3s image
      uses: actions/download-artifact@v4
      with:
        name: k3s-docker
        path: /tmp
    - name: Load K3s image
      run: docker image load -i /tmp/k3s-image.tar
    - name: Run K3s Docker Test
      run: ./scripts/test